[package]
name = "counter"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = { version = "1.2.1", features = ["derive"] }
solana-program = "3.0.0"

[dev-dependencies]
solana-program-test = "3.1.6"
solana-sdk = "3.0.0"
